### ISSUE TITLE
Ability to void transaction on server side

### ISSUE THREAD

**Issue by arunas-vareika** [iZettle/api-documentation#50]
What options do you provide to void or refund payments via REST api? SDK documentation does not mention this. 

In our use case we are integrating with 3rd party tills and in some cases order can not be fulfilled. We know if that  occurs shortly after order submission (when payment is processed already) and we would like to void such payments quickly.

What is recommended way to handle such case when using iZettle SDKs?

**Comment by FredrikMunter** [comment]
Hi @mobonapps-arunas ! Not an iOS developer, but happened to browse by. The SDK does a REST call under the hood for refunding, so I guess one could hand-craft the same request manually if the SDK gives you access to the necessary building blocks (the OAuth token for authentication, comes to mind). However, bypassing the SDK means that your integration can break at any time if we do changes to the SDK. May I ask why you specifically need a REST call, as opposed to calling the SDK's [refund method](https://github.com/iZettle/sdk-ios#refunding)? I'll try poking the iOS guys to see if they have better input...

**Comment by mobonapps-arunas** [comment]
Hi @FredrikMunter,
any option is welcome, although going "under the hood". 
We use iPad as frontend to pay & submit order to backend and sometimes fulfilment may fail. Imagine user paid for coffee and it turns out kitchen printer is offline.
All order processing steps and callbacks are on server side so REST is preferred.
Also, iOS SDK refund method requires entering password manually for each refund, so it is a bit of overhead, especially when we know for sure order failed and want to void / refund payment.

**Comment by FredrikMunter** [comment]
I understand. After an authorization (payment) has been done and approved by us, any "void" operation is technically a refund. The need for password input is a safety measure against unattended apps or lost devices, since refunding is the only "negative" business critical action one can do in the iZettle app. Quite the catastrophe for a merchant, should someone refund all of his transactions! I will forward your request to the iOS/SDK team, but I speculate that this sort of functionality would require a deeper (back end) integration to function in a secure manner.
